C4Dynamic
    title Компонентная диаграмма для интернет магазина с рекомендательной системой

    Person(c4, "Пользователи", "Покупают товары в интернете.")
    Person(c5, "Подрядчики", "Продают товары в интернете.")
    System_Boundary(b, "Интернет-Магазин") {
      Component(c1, "Сайт, Мобильное Приложение", "", "Позволяет пользователю искать и покупать товары.")
      ContainerDb(c2, "База данных", "", "Хранит актуальную информацию о товарах и пользователях.")
      Component(c3, "Рекомендательная система", "", "ML система для предоставления персонализированных рекомендаций.")
    }
    
    Rel(c5, c4, "Доставляет товары.")
    Rel(c4, c1, "Показывает пользователю товары, позволяет их купить.")
    Rel(c5, c1, "Размещает товары на сайте.")
    
    Rel(c1, c2, "Использует для показа информации.")
    Rel(c3, c2, "Использует для создания рекомендаций.")
    Rel(c3, c1, "Показывает пользователю рекомендованные товары, собирает обратную связь.")

    UpdateRelStyle(c5, c4, $textColor="red", $offsetY="50", $offsetX="-50")    
    UpdateRelStyle(c4, c1, $textColor="red", $offsetY="-50", $offsetX="-200")
    UpdateRelStyle(c5, c1, $textColor="red", $offsetY="-20", $offsetX="-40")

    UpdateRelStyle(c1, c2, $textColor="red", $offsetX="00", $offsetY="00")
    UpdateRelStyle(c3, c2, $textColor="red", $offsetX="10", $offsetY="00")
    UpdateRelStyle(c3, c1, $textColor="red", $offsetY="70", $offsetX="-220")