flowchart TD
    A{Пользователь}
    A1{Система}
    B(Список товаров)
    C(Добавление товара в корзину)
    D(Оформление заказа)
    B1(Рекомендации)
    C1(Рекомендации доп товаров)
    D1(Купленные рекомендации)

    B --- A
    C --- A
    D --- A

    A1 -->|Сбор данных о внимании пользователя| B
    A1 -->|Предложение часто покупаемых вместе товаров| C
    A1 -->|Сбор данных о купленных товарах| D
    
    
    B1 -.->|Если рекомендовано| B
    C1 -.->|Если рекомендовано| C
    D1 -.->|Если рекомендовано| D
    A1 ---->|Предложение рекомендаций для пользователя| B1
    A1 ---->|Предложение рекомендаций к товару| C1
    A1 ---->|Валидация алгоритма| D1
